version: '3.8'

services:
  configserver:
    image: 883630/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - bank-network

  accounts:
    image: 883630/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-network

  loans:
    image: 883630/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bank-network

  cards:
    image: 883630/cards:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - bank-network

networks:
  bank-network:
